name: scania-pdm-endpoint-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8       # match the base image
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - xgboost
      - joblib
      # nothing AzureML-specific needed in the scoring container

