name: scania-pdm-endpoint-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8       # match the base image
  - pip
  - pip:
      - azureml-inference-server-http
      - numpy
      - pandas
      - scikit-learn
      - xgboost
      - joblib
